### ISSUE TITLE
Audio Pipeline bug

### ISSUE THREAD

**Issue by crocodillian** [stephankokkas/Project-Echo#16]
When I run the audio preprocessing pipeline, some files end up empty on output. Some others seem fine. When trying to open the empty files, nothing plays. They are 225 bytes instead of some KB like the normal audio files. Around 30% of files are outputted empty for me.

All the files should have been outputted with data inside, Andrew and Stephan got it working on their computers.

The screenshot comes after running the preprocessing block with all optional parameters (split etc.) set to false. 

![image](https://user-images.githubusercontent.com/61301545/204973204-ad2f1bdf-add7-4f9b-bad5-0a2861c52334.png)
![image](https://user-images.githubusercontent.com/61301545/204973499-9b7bc09e-e716-480d-bb35-b0dab28cf315.png)

 - OS: Windows 10

**Comment by stephankokkas** [comment]
Thanks for that - can confirm the same files which appear empty in your environment are not empty in my environment. This may suggest a more complex issue with the environment you are running the pipeline in. Can you provide me with an export of your environment libraries and versions in a .txt file? @crocodillian

**Comment by crocodillian** [comment]
[requirements.txt](https://github.com/stephankokkas/Project-Echo/files/10129500/requirements.txt)
Is this what you're after?

**Comment by stephankokkas** [comment]
It looks like you are using your os instead of an environment - this may cause some issues with clashing environments or out-of-date libraries. Can you try creating the environment that is in the src dir (this can be done using conda with the below line of code)

```
conda env create -f env_dev.yaml
```

Once the environment build, please then execute the pipeline in the dev env and let me know how it goes.

**Comment by crocodillian** [comment]
Hi, just reinstalled it, here's the new txt file for the python libraries.

[requirements.txt](https://github.com/stephankokkas/Project-Echo/files/10129724/requirements.txt)

screenshot: 
![image](https://user-images.githubusercontent.com/61301545/204979896-231a6c1f-ca16-4181-8cd4-68acc6c515e7.png)

same files not writing properly

Still now working yet...

**Comment by crocodillian** [comment]
Ok, here's what happened. As some of the files worked and others didn't I suspected it had something to do with the bit rate. Have a look at the screenshot: 
![image](https://user-images.githubusercontent.com/61301545/205220585-950bee4b-415b-4ce7-8b66-8117ecc67e5a.png)
The ones that didn't convert all had 512kbps, whereas the ones that did had 1024 kbps. I don't think this is a coincidence. I changed the parameter bitrate = '128k' and it converted all the files for me. 
![image](https://user-images.githubusercontent.com/61301545/205221621-d2c715f5-b507-4c1c-a794-3324db27b417.png)
Is it necessary that the bitrate is 32k?

**Comment by stephankokkas** [comment]
It's still strange that all files were converted for both Andrew and myself. Nevertheless, clearly there seems to be a link between the bitrate and compatibility for conversion in your environment. I chose the value oof 32k from the EDA that was completed.  I believe the main reason the bitrate was reduced was to reduce the overall size of the tensors - the higher the bitrate the higher the quality, and therefore a larger file size. 

As this has solved the problem, I will close the issue and separately investigate.
